### ISSUE TITLE
how to implement batch spmv

### ISSUE THREAD

**Issue by zhouq123** [NVIDIA/CUDALibrarySamples#210]
i have batch matrix A and vector B, how to implement batch spmv

**Comment by qanhpham** [comment]
Hi @zhouq123, are matrices in the batch different from each other? Do they multiply with the same vector or vectors are different in the batch?

**Comment by fbusato** [comment]
please also note that the code should be similar to batched SpMM https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spmm_csr_batched

**Comment by zhouq123** [comment]
> Hi @zhouq123, are matrices in the batch different from each other? Do they multiply with the same vector or vectors are different in the batch?

yes, they are all different from each other

**Comment by zhouq123** [comment]
> please also note that the code should be similar to batched SpMM https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSE/spmm_csr_batched

but there is an error "spmm_csr_batched_example test FAILED: wrong result" when I set B_num_cols to 1 in the example of spmm_csr_batched or spmm_coo_batched

**Comment by qanhpham** [comment]
This bug has been fixed in the latest version. Please upgraded to the latest cuSPARSE to avoid this issue.

**Comment by zhouq123** [comment]
> This bug has been fixed in the latest version. Please upgraded to the latest cuSPARSE to avoid this issue.

the latest version is cuda toolkit or CUDALibrarySamples? I had upgraded to the latest CUDALibrarySamples but this issue is still exist.
